package pl.motokomando.healthcare.model.base.utils;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

public enum MedicalSpecialty {

    ANESTHESIA,
    CARDIOVASCULAR,
    COMMUNITYHEALTH,
    DENTISTRY,
    DERMATOLOGY,
    DIETNUTRITION,
    EMERGENCY,
    ENDOCRINE,
    GASTROENTEROLOGIC,
    GENETIC,
    GERIATRIC,
    GYNECOLOGIC,
    HEMATOLOGIC,
    INFECTIOUS,
    LABORATORYSCIENCE,
    MIDWIFERY,
    MUSCULOSKELETAL,
    NEUROLOGIC,
    NURSING,
    OBSTETRIC,
    ONCOLOGIC,
    OPTOMETRIC,
    OTOLARYNGOLOGIC,
    PATHOLOGY,
    PEDIATRIC,
    PHARMACYSPECIALTY,
    PHYSIOTHERAPY,
    PLASTICSURGERY,
    PODIATRIC,
    PRIMARYCARE,
    PSYCHIATRIC,
    PUBLICHEALTH,
    PULMONARY,
    RADIOGRAPHY,
    RENAL,
    RESPIRATORYTHERAPY,
    RHEUMATOLOGIC,
    SPEECHPATHOLOGY,
    SURGICAL,
    TOXICOLOGIC,
    UROLOGIC

}